services:
  db:
    image: postgres:17
    container_name: flight-postgres
    environment:
      POSTGRES_DB: flight_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: flight-app
    ports:
      - "5432:5432"
    volumes:
      - flight_postgres_data:/var/lib/postgresql/data

volumes:
  flight_postgres_data:
