spring:
  application:
    name: flight
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_db
    username: postgres
    password: flight-app
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
